export const ErrorCode = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_USER_ID: 'INVALID_USER_ID',
  INVALID_ORDER_INPUT: 'INVALID_ORDER_INPUT',
  AMOUNT_TOO_LOW: 'AMOUNT_TOO_LOW',
  INVALID_ORDER_SIDE: 'INVALID_ORDER_SIDE',
  INVALID_ORDER_TYPE: 'INVALID_ORDER_TYPE',
  INVALID_SIZE: 'INVALID_SIZE',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  INVALID_PRICE: 'INVALID_PRICE',
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  INSTRUMENT_NOT_FOUND: 'INSTRUMENT_NOT_FOUND',
  ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ORDER_NOT_CANCELLABLE: 'ORDER_NOT_CANCELLABLE',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
